### ISSUE TITLE
transfrom(变换)

### ISSUE THREAD

**Issue by 1282772905** [1282772905/Notes#3]
`transfrom`是`CSS3`提供的一个属性。

它用来*旋转*，*缩放*，*平移*，*倾斜*。

```css
.div1 {
  width: 100px;
  height: 100px;
  background-color: grey;
  transform: rotate(30deg);
}
```

### matrix
以一个含6个值的变换矩阵的形式指定2D变换。`matrix(a, b, c, d, e, f)`.不常用。
```css
.div1 {
  width: 100px;
  height: 100px;
  background-color: grey;
  transform: matrix(1, 1, 1, 0, 0, 0);
}
```

### 平移translate
两个参数。第一个参数对应X轴的平移。第二个参数对应Y轴的平移。第一个参数未提供时，第二个参数默认为0.
```css
.box {
    width: 100px;
    height: 100px;
    transform: translate(10%);
}
// 只会向右平移10px(百分比根据元素本身大小计算)
```

### 旋转rotate
以一个点为中心，做旋转。这个点可以由`transform-origin`来定义。默认是元素的中心。
```css
.box {
    width: 100px;
    height: 100px;
    transform: rotate(0.5turn);
}
// 单位：deg(度数，一圈360度)，turn(圈数，完整是一圈)
```
`transfrom-origin: (50%, 50%)`默认就是元素的中心点。

### 缩放scale
长和宽的缩放。\
⚠️注意：也是基于`transform-origin`进行缩放的。默认是在元素的中心。这样缩放会出现上和下等比缩放，左和右等比缩放。
```css
.box {
    width: 100px;
    height: 100px;
    transform: scale(2, 2);
}
// 中心点的上方增加了50px,中心点的下方增加了50px,中心点的左边增加50px,中心点的右边增加50px.
// 如果元素是在父元素的边缘，会出现部分缩放被隐藏的现象
// 如果加上transform-origin: left top;则所有增长全在右边和下方。左边不会有隐藏。
```

### 下压倾斜skew
```css
.box {
    width: 100px;
    height: 100px;
    transform: skew(45deg);
}
// 与垂直方向夹角45度。此时宽为200px。
```
