### ISSUE TITLE
transition(过渡)

### ISSUE THREAD

**Issue by 1282772905** [1282772905/Notes#4]
> 其可以让属性变化成为一个持续一段时间的过程，而不是立即生效的。比如，将一个元素的颜色从白色改为黑色，通常这个改变是立即生效的，使用 CSS transitions 后该元素的颜色将逐渐从白色变为黑色，按照一定的曲线速率变化。这个过程可以自定义。

```css
.box {
    width: 100px;
    height: 100px;
    background-color: #0000FF;
    transition: width 2s, height 2s, background-color 2s, transform 2s;
}
.box:hover {
    width: 200px;
    height: 200px;
    background-color: #333333;
    transform: rotate(180deg);
}
// 当hover的时候，元素的属性会发生一些变化，这些变化本是瞬间完成的。transition可以设置过渡。
```

`transition`其实是4个属性的简写。

```css
div {
    transition: <property> <duration> <timing-function> <delay>;
}
.box {
    transition: color 2s ease-in 0.5s;
}
```
