### ISSUE TITLE
animation(动画)

### ISSUE THREAD

**Issue by 1282772905** [1282772905/Notes#5]
`animation`是如下几个属性的简写。
> animation-name(动画名字)

> animation-duration(一次完整动画的持续时间)

> animation-timing-function(执行节奏)

> animation-delay(延迟执行)

> animation-iteration-count(动画允许次数)

> animation-direction(是否反向执行)

> animation-fill-mode(执行前后的目标样式)

```css
.box {
    animation: animate1 2s linear infinite;
}
@keyframes {
    0% {
        transfrom: scale(1.05);
    }
    100% {
        transfrom: scale(1);
    }
}
```
